Conpstone Project
Haadiiii/conference-page pull request #1
Opened 2022-07-27 20:03 UTC by Haadiiii

## microverse Capstone Project: Week5 👦 

In this Project we:
- Added 2 `HTML` file 👍 
  - One for the Desktop version
  - One for the Mobile version
- Added four `CSS` File 👍 
  - one for the mobile home page.
  - one for mobile about page.
  - one for the desktop home page.
  - one for desktop about page.
- Added `JS` file with code, functions, objects, and variables. 👍 
- Added Readme file. 👍 
- Fixed Linters. 👍 

😄  👍

2022-07-27 21:00 UTC, ShahierNashaat requested changes
Hi @Haadiiii, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 21:00 UTC, ShahierNashaat commented on README.md
> +* [Font Awesome](https://fontawesome.com)
- [ ] Kindly be noticed that you should give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-07-27 21:00 UTC, ShahierNashaat commented on README.md
- [ ] Kindly be noticed that you should make use of GitHub Pages to deploy the web pages.
- [ ] Also the link to the deployed project is present in the README.

2022-07-27 21:00 UTC, ShahierNashaat commented on home.html
> +            </div>
- [ ] Kindly fix the middle part as it goes over the right of the page.
- [ ] Also in the mobile size the middle part goes over the right of the page.

![Screenshot from 2022-07-27 22-42-54](https://user-images.githubusercontent.com/33752735/181368683-0fc95bfe-f706-497d-ae18-5f8ca6bda54e.png)
![Screenshot from 2022-07-27 22-57-44](https://user-images.githubusercontent.com/33752735/181370926-41e0a4ae-5337-48a5-84fb-0f908998efff.png)

2022-07-27 21:00 UTC, ShahierNashaat commented on about.html
> +    </section>
- [ ] Kindly in this section the dives are a little bit to the right kindly put them in the center.

![Screenshot from 2022-07-27 22-40-32](https://user-images.githubusercontent.com/33752735/181368969-e36f7ca7-ee46-4893-ae3e-9da887eeeba6.png)

2022-07-27 21:00 UTC, ShahierNashaat commented on about.html
> +            </div>
- [ ] Kindly be noticed that in the mobile size the texts go over the right of the page, please fix that.

![Screenshot from 2022-07-27 22-48-09](https://user-images.githubusercontent.com/33752735/181369645-2af92d1d-99bb-4af8-abe6-ea873abc04cf.png)

2022-07-27 21:00 UTC, ShahierNashaat commented on about.html
> +        </div>
- [ ] Kindly be noticed that the partners are going to the left of the page, please fix that.

![Screenshot from 2022-07-27 22-48-24](https://user-images.githubusercontent.com/33752735/181369881-f9d9e004-a116-4200-912c-a553ede0fe49.png)

2022-07-27 21:00 UTC, ShahierNashaat commented on home.html
> +    </section>
- [ ] Kindly be noticed the texts go over the right of the page, please fix that.

![Screenshot from 2022-07-27 22-54-22](https://user-images.githubusercontent.com/33752735/181370575-8f79446b-e98d-47ef-b131-fa1f28317425.png)

2022-07-27 21:00 UTC, ShahierNashaat commented on home.html
> +    </div>
- [ ] Same as the about page in mobile size the partners part is a little to the left please make it in the center of the page.

![Screenshot from 2022-07-27 22-58-32](https://user-images.githubusercontent.com/33752735/181371238-259b4bea-b3f3-4cdc-8a42-164f9e82f178.png)

2022-07-27 21:25 UTC, Haadiiii commented on README.md
@ShahierNashaat yeah i didnt merged the file that's why i didn't made a deployment for the page, i though ill make this after the review that's why.

2022-07-27 21:26 UTC, Haadiiii commented on home.html
> +            </div>
@ShahierNashaat  i dont know why its look like this on your side but in my side everything look perfect you can see it by yourself ill share the snaps if you.

2022-07-27 21:26 UTC, Haadiiii commented on about.html
> +    </section>
@ShahierNashaat the same thing, its looks fine from my side.

2022-07-27 21:27 UTC, Haadiiii commented on about.html
> +            </div>
@ShahierNashaat also these things also looks fine because i created the max width 768.. when you look at 767 you will see the differece.

2022-07-27 21:28 UTC, Haadiiii commented on about.html
> +        </div>
@ShahierNashaat same thing bro i dont know why am getting this review.

2022-07-27 21:28 UTC, Haadiiii commented on home.html
> +    </section>
@ShahierNashaat bro i dont know why am getting this review because no one will create his project like this its looks perfectly fine by mine side

2022-07-27 21:29 UTC, Haadiiii commented on home.html
> +    </div>
@ShahierNashaat still didn't get why am really getting this kinda review, Allthings looks fine by my side.

2022-07-28 20:47 UTC, mwanawabangona requested changes
Hi @Haadiiii , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-28 20:47 UTC, mwanawabangona commented on index.html
> +                </div>
- [ ] `required`
- [ ] good so job far 👏 
- [ ] but as the previous reviewer mentioned kindly make adjust to the mobile version on the part. please see the screenshot below for further comparisons

![image](https://user-images.githubusercontent.com/66230306/181629434-c5954dbe-c675-4e65-bfbb-65d1293fc982.png)

2022-07-28 20:47 UTC, mwanawabangona commented on index.html
> +    </footer>
- [ ] `optional`
- [ ] Kindly adjust the `partner` in the center as the design

![image](https://user-images.githubusercontent.com/66230306/181631134-17e5b022-a55d-430f-a043-a355c83383ac.png)

2022-07-28 20:47 UTC, mwanawabangona commented on index.html
> +    <section class="feature">
- [ ] `optional`
- [ ] Kindly adjust featured on the center as the original design, see `screenshots below`

`your trmplate`
![featured speakers](https://user-images.githubusercontent.com/66230306/181633167-ad09a02d-4460-4f8d-8042-438c041291cc.png)

`figma template`
![speakers](https://user-images.githubusercontent.com/66230306/181633415-8fc767b8-0b7d-4319-8a16-5c95fbbf29dd.png)

2022-07-28 20:47 UTC, mwanawabangona commented on index.html
> +
- [ ] `optional`
- [ ] Kindly fix the space on the side as the template, see screenshot below

![kk](https://user-images.githubusercontent.com/66230306/181634371-d691a047-8fcf-4e55-b8fa-811c556dcaa8.png)

2022-07-28 21:47 UTC, Haadiiii commented on index.html
> +                </div>
@mwanawabangona  thanks bro 👍

2022-07-28 21:48 UTC, Haadiiii commented on index.html
> +    </footer>
@mwanawabangona  ohh yeah minor one 😄 👍  solved

2022-07-28 21:48 UTC, Haadiiii commented on index.html
> +    <section class="feature">
@mwanawabangona  got it 👍

2022-07-28 21:48 UTC, Haadiiii commented on index.html
> +
@mwanawabangona  solved 👍

2022-07-28 22:12 UTC, algerina approved these changes
Hi @Haadiiii , 
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-31 13:00 UTC, merged